baseURL = "//cookingsimple.netlify.app/"
languageCode = "en-us"
title = "Cooking Simple"
theme = "dream"

[params]
  background = "white"
  title = "cookingsimple."
  author = "Neil Tesaluna"
  showSummaryCoverInPost = true
