baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cooking Simple"
theme = "dream"

[params]
  background = "white"
  title = "Cooking Simple"
  author = "Neil Tesaluna"
  showSummaryCoverInPost = true
