baseURL = "//simpledine.in/"
languageCode = "en-us"
title = "simpledine.in"
theme = "dream"

[params]
  background = "#e5e5e5"
  title = "simpledine.in"
  author = "Neil Tesaluna"
  avatar = "/img/avatar.jpg"
  favicon = "/img/avatar.jpg"
  showSummaryCoverInPost = true
  instagram = "bendtheneil"
  linkedin = "neil-tesaluna-a24869b7"
  github = "neiltesaluna"
