baseURL = "//cookingsimple.netlify.app/"
languageCode = "en-us"
title = "Cooking Simple"
theme = "dream"

[params]
  backgroundImage = "/img/site-bg.jpg"
  title = "cookingsimple."
  author = "Neil Tesaluna"
  showSummaryCoverInPost = true
